export const flowerStyles = {
  container: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f9f6e8',
    borderRadius: '16px',
    padding: '24px',
    minHeight: '280px',
    boxShadow: '0 8px 16px rgba(212, 143, 184, 0.1)',
    border: '2px solid rgba(212, 143, 184, 0.2)',
    overflow: 'hidden',
  },
  flowerContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    width: '100%',
    height: '60%',
    position: 'relative',
  },
  soil: {
    position: 'absolute',
    bottom: '0',
    width: '100%',
    height: '40px',
    backgroundColor: '#85634b',
    borderRadius: '0 0 16px 16px',
  },
  stem: {
    width: '6px',
    backgroundColor: '#5aaa5a',
    transition: 'height 1s ease-out',
    zIndex: 1,
  },
  flowerHead: {
    position: 'relative',
    width: '30px',
    height: '30px',
    borderRadius: '50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    transition: 'transform 1s ease-out',
    zIndex: 2,
  },
  flowerCenter: {
    width: '15px',
    height: '15px',
    borderRadius: '50%',
    backgroundColor: '#ffde59',
    transition: 'opacity 1s ease-out 0.5s',
  },
  petal: {
    position: 'absolute',
    width: '16px',
    height: '25px',
    borderRadius: '50%',
    top: '50%',
    left: '50%',
    marginLeft: '-8px',
    marginTop: '-8px',
    transition: 'opacity 1s ease-out 0.5s',
  },
  memoryText: {
    marginTop: '16px',
    padding: '16px',
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: '8px',
    textAlign: 'center',
    maxWidth: '80%',
    animation: 'fadeIn 1s ease-out',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.05)',
    zIndex: 3,
  },
}